/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d7e4ec",
        "tertiary-container": "#29353b",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3c494f",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#bbc8d0",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#ba1a20",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#410003",
        "primary-fixed-dim": "#ffb3ac",
        "on-tertiary-container": "#919ea5",
        "on-primary-fixed-variant": "#930010",
        "primary-container": "#6e0009",
        "on-surface": "#1a1c1c",
        "outline-variant": "#c3c6d1",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-background": "#1a1c1c",
        "secondary-container": "#9fc2fe",
        "on-secondary-fixed": "#001b3c",
        "surface-variant": "#e2e2e2",
        "on-secondary-container": "#294f83",
        "surface-container-high": "#e8e8e8",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "background": "#f9f9f9",
        "primary": "#460003",
        "surface-dim": "#dadada",
        "on-surface-variant": "#43474f",
        "secondary-fixed": "#d5e3ff",
        "on-secondary-fixed-variant": "#1f477b",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f1f1f1",
        "tertiary": "#142026",
        "surface-container-low": "#f3f3f3",
        "surface": "#f9f9f9",
        "secondary-fixed-dim": "#a7c8ff",
        "on-tertiary-fixed": "#111d23",
        "on-error": "#ffffff",
        "on-primary-container": "#ff6c63",
        "secondary": "#3a5f94",
        "inverse-primary": "#ffb3ac",
        "primary-fixed": "#ffdad6",
        "outline": "#737780"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}